library(tidyverse)
library(lubridate)
library(forecast)
library(zoo)
library(ggplot2)
library(scales)
library(patchwork)

# Load data for Fig 2 & 5
# Note: Using predicted values from CSVs generated by 02_Proposed_Method_ACI.R
df_aci <- read_csv("metrics_ACI_rolling_eval.csv")
df_forecasts <- read_csv("forecasts_holdout_counts_then_incidence_fixed.csv")

# Figure 2: TB Incidence Forecasts
p_forecast <- ggplot(df_forecasts) +
    annotate("rect",
        xmin = as.Date("2020-03-01"), xmax = as.Date("2021-12-31"),
        ymin = -Inf, ymax = Inf, fill = "red", alpha = 0.1
    ) +
    geom_ribbon(aes(x = Date, ymin = Lower_ACI, ymax = Upper_ACI), fill = "green", alpha = 0.2) +
    geom_line(aes(x = Date, y = Actual), color = "black", linewidth = 0.8) +
    geom_line(aes(x = Date, y = Hybrid_Point), color = "darkgreen", linewidth = 0.8) +
    labs(
        title = "TB Incidence Forecasts on Holdout Period (2017-2023)",
        subtitle = "Hybrid EEMD-SARIMA-NARNN with Adaptive Conformal Inference (ACI)",
        x = "Date", y = "Incidence per 100k"
    ) +
    theme_minimal()

ggsave("Fig2_Incidence_Forecast.pdf", p_forecast, width = 10, height = 6, device = "pdf")

# Figure 3 Panels
# (a) Rolling Coverage
p_roll <- ggplot(df_aci, aes(x = Date)) +
    annotate("rect",
        xmin = as.Date("2020-03-01"), xmax = as.Date("2021-12-31"),
        ymin = -Inf, ymax = Inf, fill = "red", alpha = 0.1
    ) +
    geom_line(aes(y = Rolling_Coverage_ACI, color = "ACI-Hybrid"), linewidth = 1) +
    geom_line(aes(y = Rolling_Coverage_Baseline, color = "Static Baseline"), linewidth = 1, linetype = "dashed") +
    geom_hline(yintercept = 0.95, color = "black", linetype = "dotted") +
    scale_color_manual(values = c("ACI-Hybrid" = "blue", "Static Baseline" = "red")) +
    labs(y = "12-month Rolling Coverage", x = "Date") +
    theme_minimal() +
    scale_y_continuous(labels = scales::percent, limits = c(0.5, 1.0))

# (b) Interval Width
p_width <- ggplot(df_aci, aes(x = Date)) +
    annotate("rect",
        xmin = as.Date("2020-03-01"), xmax = as.Date("2021-12-31"),
        ymin = -Inf, ymax = Inf, fill = "red", alpha = 0.1
    ) +
    geom_line(aes(y = MPIW_ACI), color = "darkred", linewidth = 1) +
    labs(y = "Adaptive Interval Width (MPIW)", x = "Date") +
    theme_minimal()

p_combined_3 <- (p_roll + labs(subtitle = "(a) Rolling 12-Month Coverage Probability")) /
    (p_width + labs(subtitle = "(b) Evolution of Adaptive Prediction Interval Width")) +
    plot_annotation(
        title = "Interval Performance and Adaptation Evolution",
        theme = theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 14))
    )

ggsave("Fig3_Combined_Performance.pdf", p_combined_3, width = 10, height = 10, device = "pdf")

# Figure 5: COVID Detail
p_covid <- ggplot(df_forecasts %>% filter(year(Date) %in% 2020:2021)) +
    geom_ribbon(aes(x = Date, ymin = Lower_ACI, ymax = Upper_ACI), fill = "green", alpha = 0.2) +
    geom_line(aes(x = Date, y = Actual), color = "black", linewidth = 1.2) +
    geom_line(aes(x = Date, y = Hybrid_Point), color = "darkgreen", linewidth = 1) +
    labs(
        title = "Detailed view of Forecasts during COVID-19 (2020-2021)",
        x = "Date", y = "Incidence per 100k"
    ) +
    theme_minimal()

ggsave("Fig5_Covid_Detail.pdf", p_covid, width = 10, height = 6, device = "pdf")

# Figure 6: Simulation Histogram
df_sim <- read_csv("metrics_simulation_study.csv")
p_hist <- ggplot(df_sim, aes(x = Coverage)) +
    geom_histogram(fill = "steelblue", color = "white", bins = 20) +
    geom_vline(xintercept = 0.95, color = "red", linetype = "dashed") +
    geom_vline(xintercept = 0.90, color = "orange", linetype = "dotted") +
    labs(
        title = "Simulation Validation Results (N=1,000 Scenarios)",
        x = "Empirical Coverage Probability", y = "Frequency"
    ) +
    theme_minimal()

ggsave("Fig6_Simulation_Histogram.pdf", p_hist, width = 10, height = 6, device = "pdf")

cat("Manuscript figures (PDF/Vector) successfully generated.\n")
